version: '3.1'
services:
  nginx:
    image: nginx:1.13.12-alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/:/etc/nginx/conf.d/
      - ./www/example.com/:/usr/share/nginx/html
      - ./etc/letsencrypt/live/absolutecarrentalphuket.com/fullchain.pem:/etc/letsencrypt/live/absolutecarrentalphuket.com/fullchain.pem
      - ./etc/letsencrypt/live/absolutecarrentalphuket.com/privkey.pem:/etc/letsencrypt/live/absolutecarrentalphuket.com/privkey.pem
      - ./etc/letsencrypt/dh-param/dhparam-2048.pem:/etc/ssl/certs/dhparam-2048.pem
    depends_on:
      - nodejs
  nodejs:
    image: node:9.11.1-alpine
    container_name: nodejs
    working_dir: /home/app/nodejs
    volumes:
      - ./nodejs/wanaburi:/home/app/nodejs
    ports:
      - "3000:3000"
    command: "npm start"
    expose:
      - 3000
  mysql:
    image: mysql:latest
    restart: always
    container_name: mysql
    volumes:
      - ./mysql/production:/var/lib/mysql
    environment:
      MYSQL_DATABASE: dev
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: isylzjkoot
      MYSQL_PASSWORD: isylzjkoot
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      - PMA_ARBITRARY=1
    ports:
      - 8080:80
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: isylzjkoot
      MYSQL_ROOT_PASSWORD: isylzjkoot
    links:
      - mysql_db_server:mysql


